import { createCipheriv, createDecipheriv, randomBytes } from 'node:crypto';

/**
 * v0.9.0 G1 P6 — AES-256-GCM cipher helpers for page-content (TipTap JSON).
 * Envelope: iv(12) || ct || tag(16).
 *
 * The DEK is generated by `generateDek()` from `src/lib/e2e/crypto.ts` and
 * wrapped per-recipient via `wrapDek()` / `unwrapDek()`. These helpers only
 * concern themselves with the symmetric content envelope.
 */

const IV_BYTES = 12;
const TAG_BYTES = 16;
const DEK_BYTES = 32;

export function encryptPageContent(content: unknown, dek: Buffer): Buffer {
  if (dek.byteLength !== DEK_BYTES) {
    throw new Error(`DEK must be ${DEK_BYTES} bytes, got ${dek.byteLength}`);
  }
  const iv = randomBytes(IV_BYTES);
  const cipher = createCipheriv('aes-256-gcm', dek, iv);
  const pt = Buffer.from(JSON.stringify(content), 'utf8');
  const ct = Buffer.concat([cipher.update(pt), cipher.final()]);
  const tag = cipher.getAuthTag();
  return Buffer.concat([iv, ct, tag]);
}

export function decryptPageContent(blob: Buffer, dek: Buffer): unknown {
  if (dek.byteLength !== DEK_BYTES) {
    throw new Error(`DEK must be ${DEK_BYTES} bytes, got ${dek.byteLength}`);
  }
  if (blob.byteLength < IV_BYTES + TAG_BYTES) {
    throw new Error('encrypted blob too short');
  }
  const iv = blob.subarray(0, IV_BYTES);
  const tag = blob.subarray(blob.length - TAG_BYTES);
  const ct = blob.subarray(IV_BYTES, blob.length - TAG_BYTES);
  const decipher = createDecipheriv('aes-256-gcm', dek, iv);
  decipher.setAuthTag(tag);
  const pt = Buffer.concat([decipher.update(ct), decipher.final()]);
  return JSON.parse(pt.toString('utf8'));
}
