// AUTO-GENERATED by scripts/generate-release-notes.mjs (`pnpm notes:gen`) — do not edit.
// Drift guard: tests/scripts/generate-release-notes.test.ts. Excluded from Biome.

export type ReleaseNotes = {
  /** package.json version the notes were extracted for. */
  version: string;
  /** Matching CHANGELOG.md section (incl. heading), or null when absent. */
  markdown: string | null;
};

export const releaseNotes: ReleaseNotes = {
  version: "0.10.1",
  markdown: "## [0.10.1] - 2026-06-11\n\nTwo quality-of-life fixes for self-hosted deployments, straight off the\nv0.10.0 punch list.\n\n### Added\n\n- **Manual OAuth client provisioning:** admins can create OAuth client\n  credentials directly from Settings → Admin → OAuth clients — name,\n  redirect URIs, and a public/confidential toggle. The client secret is\n  shown exactly once at creation (sha256 at rest) with copy buttons, and\n  confidential clients gain a rotate-secret row action. This unblocks MCP\n  clients on LAN-only deployments that cannot use RFC 7591 dynamic\n  registration.\n\n### Fixed\n\n- **Settings navigation dead end:** the settings hub had no route back to\n  the app — the workspace sidebar unmounts on `/settings/*` and every nav\n  target stayed inside the hub. The settings sidebar now leads with a\n  \"Back to workspace\" link (keyboard-navigable, first in arrow-key order).",
};
