import type { AssetRef } from '../assets';
import { applyFrontmatter } from '../frontmatter';

/**
 * Per-page input the Docusaurus tree builder consumes. Mirrors `RenderedPage`
 * from the MkDocs builder so the orchestrator can hand the same array to
 * either target (only the frontmatter shape differs).
 */
export type DocusaurusPageInput = {
  id: string;
  parentId: string | null;
  title: string;
  slug: string;
  /**
   * Sidebar position. Derived by the orchestrator from depth-first walk
   * order (canonical insertion order — see `walkWorkspacePages`).
   */
  navOrder: number;
  depth: number;
  markdown: string;
};

export type DocusaurusTree = {
  files: Record<string, string | Buffer>;
};

/**
 * Group of locale → translated page for the same logical page. Built by the
 * orchestrator from `pages.translation_of_page_id` / `pages.translation_locale`.
 * Map key: the canonical (non-translation) page id. Value: locale → translated
 * page in the same shape as the canonical pages array.
 */
export type TranslationGroups = Map<string, Record<string, DocusaurusPageInput>>;

type SidebarItem = string | { type: 'category'; label: string; items: SidebarItem[] };

function buildSidebar(pages: DocusaurusPageInput[]): SidebarItem[] {
  const childrenByParent = new Map<string | null, DocusaurusPageInput[]>();
  for (const p of pages) {
    const arr = childrenByParent.get(p.parentId) ?? [];
    arr.push(p);
    childrenByParent.set(p.parentId, arr);
  }
  function emit(parentId: string | null): SidebarItem[] {
    const kids = (childrenByParent.get(parentId) ?? []).sort((a, b) => a.navOrder - b.navOrder);
    return kids.map<SidebarItem>((k) => {
      const grandkids = emit(k.id);
      if (grandkids.length === 0) return k.slug;
      return { type: 'category', label: k.title, items: [k.slug, ...grandkids] };
    });
  }
  return emit(null);
}

function escapeJsString(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function stringifySidebarItem(item: SidebarItem): string {
  if (typeof item === 'string') return `'${escapeJsString(item)}'`;
  const items = item.items.map(stringifySidebarItem).join(', ');
  return `{ type: 'category', label: '${escapeJsString(item.label)}', items: [${items}] }`;
}

/**
 * Build the Docusaurus project file map: `docusaurus.config.js`, `sidebars.js`,
 * one `docs/<slug>.md` per page (with Docusaurus frontmatter), and
 * `docs/assets/<filename>` for every bundled asset. Parallel-translation pages
 * (P26's `pages.translation_of_page_id`) land under
 * `i18n/<locale>/docusaurus-plugin-content-docs/current/`.
 */
export function buildDocusaurusTree(args: {
  workspaceName: string;
  pages: DocusaurusPageInput[];
  assets: Array<AssetRef & { contents: Buffer }>;
  translationGroups: TranslationGroups;
}): DocusaurusTree {
  const files: Record<string, string | Buffer> = {};

  // 1. Per-page markdown with Docusaurus frontmatter.
  for (const p of args.pages) {
    files[`docs/${p.slug}.md`] = applyFrontmatter(
      'docusaurus',
      { id: p.id, title: p.title, slug: p.slug, navOrder: p.navOrder, depth: p.depth },
      p.markdown,
    );
  }

  // 2. Assets.
  for (const a of args.assets) {
    files[`docs/assets/${a.destFilename}`] = a.contents;
  }

  // 3. sidebars.js — mirrors the page tree.
  const sidebar = buildSidebar(args.pages);
  const sidebarJs = sidebar.map(stringifySidebarItem).join(',\n    ');
  files['sidebars.js'] = `// Generated by cairn-export. Do not edit by hand.
module.exports = {
  docs: [
    ${sidebarJs}
  ],
};
`;

  // 4. docusaurus.config.js — minimal valid config.
  const wsTitle = escapeJsString(args.workspaceName);
  files['docusaurus.config.js'] = `// Generated by cairn-export. Do not edit by hand.
/** @type {import('@docusaurus/types').Config} */
module.exports = {
  title: '${wsTitle}',
  tagline: 'Generated by Cairn',
  url: 'https://example.com',
  baseUrl: '/',
  organizationName: 'cairn',
  projectName: '${wsTitle}',
  presets: [
    [
      '@docusaurus/preset-classic',
      {
        docs: {
          sidebarPath: require.resolve('./sidebars.js'),
        },
      },
    ],
  ],
};
`;

  // 5. i18n directory tree for parallel-translation pages.
  for (const [, byLocale] of args.translationGroups) {
    for (const [locale, page] of Object.entries(byLocale)) {
      const dir = `i18n/${locale}/docusaurus-plugin-content-docs/current`;
      files[`${dir}/${page.slug}.md`] = applyFrontmatter(
        'docusaurus',
        {
          id: page.id,
          title: page.title,
          slug: page.slug,
          navOrder: page.navOrder,
          depth: page.depth,
        },
        page.markdown,
      );
    }
  }

  return { files };
}
